version: '3.10'

services:
  api:
    build:
      context: ./app/backend/
    ports:
      - "8001:8001"
    volumes:
      - ./app/backend:/app
    command: "uvicorn main:app --host 0.0.0.0 --port 8001 --reload"
    restart: always
    networks:
        - app
    container_name: api

  ui:
    build:
      context: ./app/frontend/
    ports:
      - "8501:8501"
    volumes:
      - ./app/frontend:/app
    restart: always
    networks:
        - app
    container_name: ui

networks:
  app:
    driver: bridge